uk_main/urls.py
from uk_main.view.chats.chats.create_chat import ChatCreateView
from django.urls import path

from . import views

urlpatterns = [
    path("", views.MainView.as_view(), name="main"),
    path("news", views.NewsListView.as_view(), name="news"),
    path("news/<int:news_id>", views.NewsRetriveView.as_view(), name="news_retrive"),
    path("comment/<int:news_id>", views.CreateCommentView.as_view(), name="comment_create"),
    path("comment/delete/<int:comment_id>", views.CommentDeleteView.as_view(), name="comment_delete"),
    path("npa", views.NPAView.as_view(), name="npa"),
    path("pw", views.PerfomedWorksListView.as_view(), name="perfomed_work"),
    path("pw/<int:address_pk>/", views.PerfomedWorkRetrive.as_view(), name="pw"),
    path(
        "pw/<int:address_pk>/<int:year>/<int:quarter>",
        views.PerfomedWorkRetriveByQuarterYear.as_view(),
        name="pwQY",
    ),
    path("license", views.LicenseView.as_view(), name="license"),
    path("requisite", views.RequisitesView.as_view(), name="requisites"),
    path("homelist", views.HomeListView.as_view(), name="homelist"),
    path("homelist/<int:address_pk>", views.HomeRetriveView.as_view(), name="home_info"),
    path("profile/<int:user_id>", views.SettingsView.as_view(), name="settings"),
    path("set_address/", views.SettingsView.as_view(), name="set_address"),
    path("requests_disp/", views.DispetherRequestsView.as_view(), name="reqeusts_dispetcher"),
    path(
        "requests_disp/<int:request_id>/", views.DispetherRequestsView.as_view(), name="reqeusts_dispetcher"
    ),
    path("requests/", views.UserRequestsView.as_view(), name="request"),
    path("requests/create/", views.RequestAddView.as_view(), name="request_add"),
    path("request/star/<int:pk>", views.RequestStar.as_view(), name="request_star"),
    path(
        "requests/delete/<int:request_pk>/",
        views.RequestDeleteView.as_view(),
        name="request_delete",
    ),
    path("chat/create/<int:user_id>", views.ChatCreateView.as_view(), name="create_chat"),
    path("ms/", views.ChatListView.as_view(), name="chats"),
    path("ms/create/<int:chat_id>", views.CreateMessageView.as_view(), name="create_mess"),
    path("meters/", views.WaterMeterView.as_view(), name="water_meters"),
    path("meters/create/", views.WaterMeterAddView.as_view(), name="water_meters_add"),
    path(
        "meters/delete/<int:meter_pk>/",
        views.WaterMeterDeleteView.as_view(),
        name="water_meters_delete",
    ),
]

uk_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('uk_main.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

uk_main/models/houses.py
from django.db.models import (
    Model,
    CharField,
    TextField,
    IntegerField,
    FileField,
    DateField,
    ForeignKey,
    CASCADE,
)
from .user import CustomUser as User


class Address(Model):
    street_name = CharField("Улица", max_length=255)

    def __str__(self) -> str:
        return self.street_name

    class Meta:
        verbose_name = "Адрес"
        verbose_name_plural = "Адреса"


class House(Model):
    address_id = CharField("Id дома в базе РеформаЖКХ", max_length=100, blank=True, null=True)
    outside = CharField("Улица", max_length=100)
    house = CharField("Дом", max_length=100)
    body = CharField("Корпус", max_length=100, blank=True, null=True)
    apartament = IntegerField("Квартира", blank=True, null=True)
    area = CharField("Общая площадь", max_length=100, blank=True, null=True)
    basis_for_managment = CharField("Основания для управления", max_length=256, blank=True, null=True)
    date_managment_start = DateField("Дата начала управления", blank=True, null=True)
    area_life = CharField("Жилая площадь", max_length=100, blank=True, null=True)
    floors = IntegerField("Количество этажей", blank=True, null=True)
    entrances = IntegerField("Количество подъездов", blank=True, null=True)
    year_of_house = IntegerField("Год ввода дома в эксплуатацию", blank=True, null=True)
    managment_file = FileField(
        "Файл, приказ, основание для управления", upload_to="manage_file_house", blank=True, null=True
    )
    reforma_zkh_url = TextField("Ссылка на реформу жкх", blank=True, null=True)
    lodger = ForeignKey(
        User, on_delete=CASCADE, blank=True, null=True, default=None, verbose_name="Владелец"
    )

    def __str__(self):

        """Проверка корпуса"""
        if self.body:
            body = f"{self.body} "
        else:
            body = " "

        """Проверка Квартиры"""
        if self.apartament:
            apartament = f"кв. {self.apartament}"
        else:
            apartament = " "

        return "{} д.{}{}".format(self.outside, str(self.house) + body, apartament)

    def get_file_name(self):

        return self.managment_file.name.split("/")[1]

    class Meta:
        verbose_name = "Дом у правлении"
        verbose_name_plural = "Дома в управлении"

uk_main/models/perfomed_work.py
from django.db.models import Model, CharField, TextField, FileField, ForeignKey, CASCADE
from .houses import Address


class PerfomedWork(Model):
    file_name = CharField("Имя файла, которое будет отображаться на сайте", max_length=100)
    description = TextField(
        "Описание, которое отображается перед файлом", default=None, blank=True, null=True
    )
    file = FileField("Файл", upload_to="perfomed_work")
    quarter = CharField("Квартал", max_length=255, blank=True, null=True, default=None)
    year = CharField("Год", max_length=255, blank=True, null=True, default=None)
    address = ForeignKey(
        Address, on_delete=CASCADE, blank=True, null=True, default=None, verbose_name="Адрес"
    )

    def __str__(self) -> str:
        return self.file_name

    class Meta:
        verbose_name = "Выполненные работы по текущему ремонту"
        verbose_name_plural = "Выполненные работы по текущему ремонту"

templates/perfomed_work/perfomed_work.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="col-6">
    <div class="div-h-texts"><p class="h-texts">Выполненные работы по текущему ремонту</p></div>
    {% if address_list.0 is None  %}
            <div class="div-h-texts">
                <p class="h-texts">Упс, тут пусто, подождите, может появятся позже :(</p>
            </div>
    {% endif %}
    {% comment %} {% for perfomed_work in perfomed_works_list %}
    <a class="file-link" href="{{ perfomed_work.file.url }}">{{ perfomed_work.file_name }}</a>
    {% endfor %} {% endcomment %}
    {% for address in address_list %}
        <div class="div-h-texts"><h5 class="h-texts"><a href="{% url 'pw' address.pk %}">{{address.street_name}}</a></h5></div>
    {% endfor %}
    </div>
    {% include 'include/notifications.html' %}
{% endblock content %}

templates/perfomed_work/perfomed_work_ret.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="col-6">
    <div class="div-h-texts"><p class="h-texts">улица {{address.street_name}}</p</div>
    <div class="div-h-texts"><p class="h-texts"><a class="link-body" href="{% url 'perfomed_work' %}">← вернуться назад</a></p></div>
    {% comment %} {% for perfomed_work in perfomed_works_list %}
    <a class="file-link" href="{{ perfomed_work.file.url }}">{{ perfomed_work.file_name }}</a>
    {% endfor %} {% endcomment %}
    {% for value in values_list %}
        <div class="div-h-texts"><h5 class="h-texts"><a href="{% url 'pwQY' address.pk  value.0  value.1%}">{{value.1}} квартал {{value.0}} года</a></h5></div>
    {% endfor %}
    </div>
    {% include 'include/notifications.html' %}
{% endblock content %}

templates/perfomed_work/perfomed_work_ret_quarter_year.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="col-6">
    <div class="div-h-texts"><p class="h-texts">улица {{address.street_name}}, {{ quarter }} квартал {{ year }} год</p></div>
    <div class="div-h-texts"><p class="h-texts"><a class="link-body" href="{% url 'pw' address.pk%}">← вернуться назад</a></p></div>
    {% for file in file_list %}
    <div>
        {% if file.description != None%}
            <div class="desc-file-text">{{ file.description }}</div>
        {% endif %}
        <div class="div-h-texts"><p class="h-texts"><a class="file-link" href="{{ file.file.url }}">{{ file.file_name }}</a></p></div>
    </div>
    {% endfor %}
    </div>
    {% include 'include/notifications.html' %}
{% endblock content %}