uk_main/urls.py
from uk_main.view.chats.chats.create_chat import ChatCreateView
from django.urls import path

from . import views

urlpatterns = [
    path("", views.MainView.as_view(), name="main"),
    path("news", views.NewsListView.as_view(), name="news"),
    path("news/<int:news_id>", views.NewsRetriveView.as_view(), name="news_retrive"),
    path("comment/<int:news_id>", views.CreateCommentView.as_view(), name="comment_create"),
    path("comment/delete/<int:comment_id>", views.CommentDeleteView.as_view(), name="comment_delete"),
    path("npa", views.NPAView.as_view(), name="npa"),
    path("pw", views.PerfomedWorksListView.as_view(), name="perfomed_work"),
    path("pw/<int:address_pk>/", views.PerfomedWorkRetrive.as_view(), name="pw"),
    path(
        "pw/<int:address_pk>/<int:year>/<int:quarter>",
        views.PerfomedWorkRetriveByQuarterYear.as_view(),
        name="pwQY",
    ),
    path("license", views.LicenseView.as_view(), name="license"),
    path("requisite", views.RequisitesView.as_view(), name="requisites"),
    path("homelist", views.HomeListView.as_view(), name="homelist"),
    path("homelist/<int:address_pk>", views.HomeRetriveView.as_view(), name="home_info"),
    path("profile/<int:user_id>", views.SettingsView.as_view(), name="settings"),
    path("set_address/", views.SettingsView.as_view(), name="set_address"),
    path("requests_disp/", views.DispetherRequestsView.as_view(), name="reqeusts_dispetcher"),
    path(
        "requests_disp/<int:request_id>/", views.DispetherRequestsView.as_view(), name="reqeusts_dispetcher"
    ),
    path("requests/", views.UserRequestsView.as_view(), name="request"),
    path("requests/create/", views.RequestAddView.as_view(), name="request_add"),
    path("request/star/<int:pk>", views.RequestStar.as_view(), name="request_star"),
    path(
        "requests/delete/<int:request_pk>/",
        views.RequestDeleteView.as_view(),
        name="request_delete",
    ),
    path("chat/create/<int:user_id>", views.ChatCreateView.as_view(), name="create_chat"),
    path("ms/", views.ChatListView.as_view(), name="chats"),
    path("ms/create/<int:chat_id>", views.CreateMessageView.as_view(), name="create_mess"),
    path("meters/", views.WaterMeterView.as_view(), name="water_meters"),
    path("meters/create/", views.WaterMeterAddView.as_view(), name="water_meters_add"),
    path(
        "meters/delete/<int:meter_pk>/",
        views.WaterMeterDeleteView.as_view(),
        name="water_meters_delete",
    ),
]

uk_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('uk_main.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

uk_main/models/chats.py
from django.db.models import (
    Model,
    CharField,
    TextField,
    BooleanField,
    ForeignKey,
    DateTimeField,
    ManyToManyField,
    NOT_PROVIDED,
    DO_NOTHING,
    SET_NULL,
)
from django.utils import timezone
from .user import CustomUser as User


class Chat(Model):

    DIALOG = "D"
    CHAT = "C"
    CHAT_TYPE_CHOICES = ((DIALOG, "Dialog"), (CHAT, "Chat"))

    type = CharField("Тип", max_length=1, choices=CHAT_TYPE_CHOICES, default=DIALOG)
    members = ManyToManyField(User, verbose_name="Участник", related_name="chats")
    updated = DateTimeField("Последнее обновление чата", default=timezone.now)

    def __str__(self):
        members = ""
        for member in self.members.all():
            members += member.get_short_name() + ", "
        return "Тип чата {}. Участники: {}.".format(self.type, members)

    class Meta:
        verbose_name = "Чат"
        verbose_name_plural = "Чаты"


class Message(Model):
    chat = ForeignKey(Chat, verbose_name="Чат", null=True, blank=True, on_delete=SET_NULL)
    author = ForeignKey(User, verbose_name="Пользователь", null=True, blank=True, on_delete=SET_NULL)
    message = TextField("Сообщение")
    pub_date = DateTimeField("Дата сообщения", default=timezone.now)
    is_readed = BooleanField("Прочитано", default=False)

    def __str__(self):
        return "Отправитель {} Чат {}".format(self.author, self.chat)

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"
        ordering = ["pub_date"]

templates/chats/chats.html
{% extends 'base.html' %}
{% load tz %}
{% load get_companion %}
{% load static %}
{% block content %}

<div class="col-10 row chats-div">
    <div class="col-3 dialogs">
        <div class="search-chat"> 
            <img src="{% static 'imgs/SVG/search.svg' %}" alt="">
            <div class="btn-group">
                <button type="button" class="btn-account dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                Поиск
                </button>
                <ul class="dropdown-menu">
                {% for user_drop in all_users %}
                    {% if all_users.first != user_drop%}
                        <li><hr class="dropdown-divider"></li>
                    {% endif %}
                    <li>
                        <a class="dropdown-item" href="{% url 'create_chat' user_drop.id %}" method='POST'>
                            <div class="flex-settings">
                                <div class='chat-photo-div'>
                                    {% if user_drop.profile_image.first != None%}
                                    <img src="{{ user_drop.profile_image.first.profile_image.url}}" alt="" class="chat-photo">
                                    {%else%}
                                    <img src="../static/default_profile.png" alt="" class="chat-photo">
                                    {% endif %}
                                </div>
                                <div>
                                    {{user_drop.last_name}} {{user_drop.first_name}}
                                </div>
                            </div>
                            
                            {% if user_drop.is_staff == True %}
                                <strong>Сотрудник</strong>
                            {% endif %}
                        </a>
                    </li>
                {% endfor %}
                </ul>
            </div> 
        </div>
        
        {% if chats.count == 0 %}
        <div class='no-such-dialogs'>Нет ни одного начатого диалога</div>
        {% endif %}
        
        {% for chat in chats %}
            {% if chat %}
                {% with last_message=chat.message_set.last %}
                    {% get_companion user chat as companion %}
                    <a class="chat-group-item {% if companion == last_message.author and not last_message.is_readed %}unreaded{% endif %} {% if chat.id == chat_id %}active-chat{% endif %}" href="{% url 'chats' %}?im={{ chat.id }}">
                        <div class="reply-body">
                            <ul class="list-chat-inline">
                                <li class="drop-left-padding">
                                    <strong class="list-group-item-heading">{{ companion }}</strong>
                                </li>
                                <li class="text-muted"><small>{{last_message.pub_date|date:'H:i'}}</small></li>
                            </ul>
                            {% if companion != last_message.author %}
                                <div>
                                    <div class="text-msg {% if not last_message.is_readed %}unreaded{% endif %}">{{ last_message.message|truncatechars_html:"15"|safe|striptags }}</div>
                                </div>
                            {% else %}
                                <div class="text-msg">{{ last_message.message|truncatechars_html:"15"|safe|striptags }}</div>
                            {% endif %}
                        </div>
                    </a>
                {% endwith %}
            {% endif %}
        {% endfor %}
    </div>
    <div class="col-9 div-for-messages">
    {% if messeges.0 != None%}
        {% get_sobes user chat_id as sobesednik %}
        <div class='chat-user-name'><a href="{% url 'settings' sobesednik.id %}"><strong>{{ sobesednik.get_short_name }}</strong></a></div>
        <div class="messages">
            <div class="padding-for-messages-divs">
                {% for mes in messeges %}
                    {% if mes.author == user %}
                    <div class="message-div-sender">
                        <div class="time-message">{{mes.pub_date|date:'H:i'}}</div>
                        <div class="message user-sender">{{mes.message}}</div>
                    </div>
                    {% else %}
                    <div class="message-div-host">
                        <div class="message user-host">{{mes.message}}</div>
                        <div class="time-message">{{mes.pub_date|date:'H:i'}}</div>
                    </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <form action="{% url 'create_mess' chat_id %}" method=POST class='message-form'>
            {% csrf_token %}
            <textarea class="textarea-message" placeholder="Введите сообщение" name="message" id="" cols="30" rows="10"></textarea>
            <button class="message-send-btn"></button>
        </form>
    {% elif chat_id != None %}
        {% get_sobes user chat_id as sobesednik %}
        <div class='chat-user-name'><a href="{% url 'settings' sobesednik.id %}"><strong>{{ sobesednik.get_short_name }}</strong></a></div>
        <div class="messages">
            <div class="padding-for-messages-divs">
                {% for mes in messeges %}
                    {% if mes.author == user %}
                    <div class="message-div-sender">
                        <div class="time-message">{{mes.pub_date|date:'H:i'}}</div>
                        <div class="message user-sender">{{mes.message}}</div>
                    </div>
                    {% else %}
                    <div class="message-div-host">
                        <div class="message user-host">{{mes.message}}</div>
                        <div class="time-message">{{mes.pub_date|date:'H:i'}}</div>
                    </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <form action="{% url 'create_mess' chat_id %}" method=POST class='message-form'>
            {% csrf_token %}
            <textarea class="textarea-message" placeholder="Введите сообщение" name="message" id="" cols="30" rows="10"></textarea>
            <button class="message-send-btn"></button>
        </form>
    {% endif %}
    </div>
    

</div>

{% endblock content %}